INSERT INTO public.vocab (term, definition, category) VALUES
('Fiduciary Duty', 'An obligation to act in the best interest of the client.', 'Ethics'),
('Suitability', 'Ensuring an investment recommendation fits the client’s financial situation.', 'Ethics'),
('Inflation', 'The rate at which the general level of prices for goods and services rises.', 'Economics'),
('Gross Domestic Product (GDP)', 'The total value of goods and services produced within a country.', 'Economics'),
('Standard Deviation', 'A measure of the dispersion or variability of a set of data.', 'Quantitative'),
('Correlation', 'A statistical measure that indicates the extent to which two variables move in relation to each other.', 'Quantitative'),
('Asset Allocation', 'The process of dividing investments among different asset categories.', 'Portfolio Management'),
('Diversification', 'Reducing risk by investing in a variety of assets.', 'Portfolio Management'),
('Securities Act of 1933', 'Regulates the initial sale of securities to the public.', 'Regulation'),
('Investment Advisers Act of 1940', 'Regulates investment advisers and their fiduciary responsibilities.', 'Regulation'),
('Defined Benefit Plan', 'A retirement plan that promises a specified monthly benefit at retirement.', 'Retirement Planning'),
('Defined Contribution Plan', 'A retirement plan where contributions are defined but benefits vary.', 'Retirement Planning'),
('Capital Gains Tax', 'Tax on the profit from the sale of an asset.', 'Taxation'),
('Tax-Deferred', 'Earnings on an investment that are not taxed until withdrawn.', 'Taxation'),
('Mutual Fund', 'An investment vehicle pooling money from many investors to buy securities.', 'Investment Vehicles'),
('Exchange-Traded Fund (ETF)', 'A fund traded on stock exchanges, holding assets like stocks or bonds.', 'Investment Vehicles'),
('Systematic Risk', 'Risk inherent to the entire market or market segment.', 'Risk'),
('Unsystematic Risk', 'Risk specific to a company or industry.', 'Risk'),
('Churning', 'Excessive trading by a broker to generate commissions.', 'Ethics'),
('Liquidity', 'The ease with which an asset can be converted to cash.', 'Economics'),
('Alpha', 'A measure of an investment’s performance relative to a benchmark.', 'Portfolio Management'),
('Beta', 'A measure of a security’s volatility compared to the market.', 'Quantitative'),
('ERISA', 'Employee Retirement Income Security Act governing retirement plans.', 'Regulation'),
('Roth IRA', 'An individual retirement account with tax-free withdrawals.', 'Retirement Planning'),
('Wash Sale Rule', 'IRS rule disallowing a loss deduction if a security is repurchased within 30 days.', 'Taxation');
